// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentInformationSystem_Test.Context;

namespace StudentInformationSystem_Test.Migrations
{
    [DbContext(typeof(SISEntityContext))]
    partial class SISEntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DepartmentEntityLectureEntity", b =>
                {
                    b.Property<Guid>("DepartmentEntitiesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LectureEntitiesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DepartmentEntitiesId", "LectureEntitiesId");

                    b.HasIndex("LectureEntitiesId");

                    b.ToTable("DepartmentEntityLectureEntity");
                });

            modelBuilder.Entity("StudentInformationSystem_Test.Models.DepartmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("DepartmentEntities");
                });

            modelBuilder.Entity("StudentInformationSystem_Test.Models.LectureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("StudentEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentEntityId");

                    b.ToTable("LectureEntities");
                });

            modelBuilder.Entity("StudentInformationSystem_Test.Models.StudentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("StudentEntities");
                });

            modelBuilder.Entity("DepartmentEntityLectureEntity", b =>
                {
                    b.HasOne("StudentInformationSystem_Test.Models.DepartmentEntity", null)
                        .WithMany()
                        .HasForeignKey("DepartmentEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentInformationSystem_Test.Models.LectureEntity", null)
                        .WithMany()
                        .HasForeignKey("LectureEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentInformationSystem_Test.Models.LectureEntity", b =>
                {
                    b.HasOne("StudentInformationSystem_Test.Models.StudentEntity", null)
                        .WithMany("LectureEntities")
                        .HasForeignKey("StudentEntityId");
                });

            modelBuilder.Entity("StudentInformationSystem_Test.Models.StudentEntity", b =>
                {
                    b.HasOne("StudentInformationSystem_Test.Models.DepartmentEntity", "Department")
                        .WithMany("StudentEntities")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentInformationSystem_Test.Models.DepartmentEntity", b =>
                {
                    b.Navigation("StudentEntities");
                });

            modelBuilder.Entity("StudentInformationSystem_Test.Models.StudentEntity", b =>
                {
                    b.Navigation("LectureEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
